"""Add ytd_return and average_delay to Tracker

Revision ID: c36b439e21c7
Revises: 
Create Date: 2025-11-22 07:03:57.887645

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c36b439e21c7'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tracker', sa.Column('ytd_return', sa.Float(), nullable=False))
    op.add_column('tracker', sa.Column('average_delay', sa.Integer(), nullable=False))
    op.drop_column('tracker', 'one_year_return')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tracker', sa.Column('one_year_return', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.drop_column('tracker', 'average_delay')
    op.drop_column('tracker', 'ytd_return')
    # ### end Alembic commands ###
